/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      "colors": {
          "primary-fixed-dim": "#adc6ff",
          "surface-container-low": "#0b1c30",
          "surface-variant": "#26364a",
          "on-tertiary-fixed": "#410004",
          "surface-container-highest": "#26364a",
          "secondary": "#00ff87",
          "primary": "#adc6ff",
          "tertiary-fixed-dim": "#ffb3ad",
          "on-primary-container": "#00285d",
          "secondary-fixed-dim": "#4edea3",
          "outline-variant": "#424754",
          "tertiary": "#ffb3ad",
          "tertiary-fixed": "#ffdad7",
          "surface": "#031427",
          "on-primary": "#002e6a",
          "secondary-container": "#00a572",
          "primary-fixed": "#d8e2ff",
          "on-surface": "#d3e4fe",
          "outline": "#8c909f",
          "inverse-primary": "#005ac2",
          "error-container": "#93000a",
          "on-secondary-fixed-variant": "#005236",
          "on-primary-fixed": "#001a42",
          "on-secondary-container": "#00311f",
          "on-tertiary-container": "#5c0008",
          "inverse-surface": "#d3e4fe",
          "on-primary-fixed-variant": "#004395",
          "on-background": "#d3e4fe",
          "surface-container": "#102034",
          "surface-container-lowest": "#000f21",
          "surface-container-high": "#1b2b3f",
          "secondary-fixed": "#6ffbbe",
          "on-secondary": "#003824",
          "primary-container": "#4d8eff",
          "error": "#ffb4ab",
          "on-secondary-fixed": "#002113",
          "on-surface-variant": "#c2c6d6",
          "on-error-container": "#ffdad6",
          "tertiary-container": "#ff5451",
          "on-tertiary-fixed-variant": "#930013",
          "surface-dim": "#031427",
          "surface-tint": "#adc6ff",
          "background": "#031427",
          "surface-bright": "#2a3a4f",
          "on-tertiary": "#68000a",
          "on-error": "#690005",
          "inverse-on-surface": "#213145"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "element-gap-sm": "4px",
          "section-gap": "24px",
          "gutter": "12px",
          "element-gap-md": "8px",
          "container-padding": "16px",
          "unit": "4px"
      },
      "fontFamily": {
          "body-lg": ["Inter"],
          "mono-data": ["Inter"],
          "label-caps": ["Inter"],
          "body-sm": ["Inter"],
          "body-md": ["Inter"],
          "headline": ["Work Sans"],
          "display": ["Work Sans"]
      },
      "fontSize": {
          "body-lg": ["15px", {"lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400"}],
          "mono-data": ["13px", {"lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
          "body-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400"}],
          "body-md": ["13px", {"lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400"}],
          "headline": ["18px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "display": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};