trigger:
- main

variables:
  backendImage: 'kalharanuwan/tradex-backend'
  frontendImage: 'kalharanuwan/tradex-frontend'

stages:

- stage: BuildAndPush
  displayName: Build and Push Images
  jobs:
  - job: BuildBackend
    displayName: Build Backend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: '$(backendImage)'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        buildContext: '.'
        tags: |
          latest

  - job: BuildFrontend
    displayName: Build Frontend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: '$(frontendImage)'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        buildContext: '.'
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: Deploy Backend
      inputs:
        azureSubscription: 'azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name tradex-backend \
            --resource-group kalhara \
            --image $(backendImage):latest

    - task: AzureCLI@2
      displayName: Deploy Frontend
      inputs:
        azureSubscription: 'azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name tradex-frontend \
            --resource-group kalhara \
            --image $(frontendImage):latest
