version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    # environment:
    #   - MONOG_URI=mongodb://mongo:27017/Crypto # Uncomment if using a mongo container

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
